version: '3.8'

services:

    db:
        image: 'postgres:13.1-alpine'
        container_name: camellia-db
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=camellia
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=camellia-cultivar

    server:
        build:
            context: ./camellia
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - '8085:8085'
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/camellia-cultivar
            - SPRING_DATASOURCE_DATABASE=camellia-cultivar
            - SPRING_DATASOURCE_USERNAME=camellia
            - SPRING_DATASOURCE_PASSWORD=password
            #- SPRING_JPA_HIBERNATE_DDL_AUTO=update  
