/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlowerIcon
///      fonts:
///       - asset: fonts/FlowerIcon.ttf
///
///
///
///
import 'package:flutter/widgets.dart';

class FlowerIcon {
  FlowerIcon._();

  static const _kFontFam = 'FlowerIcon';
  static const String? _kFontPkg = null;

  static const IconData new_specimen3 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
